AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Resources:
  LambdaPaymentFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: lambda-payment-function
      Handler: index.lambda_handler
      Runtime: nodejs22.x
      CodeUri: ../lambda-payment-function/dist
      MemorySize: 128
      Timeout: 28
      Architectures:
        - arm64
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          ENV: production
          BuildTimestamp: !Ref BuildTimestamp
      AutoPublishAlias: live
      DeploymentPreference:
        Enabled: true
        Type: AllAtOnce
    DependsOn: EventBus

  BenefitsRule:
    Type: AWS::Events::Rule
    Properties:
      EventBusName: !Ref EventBus
      Name: benefits-rule
      EventPattern:
        detail-type:
          - payment
      Targets:
        - Id: BenefitsQueueTarget
          Arn: !GetAtt BenefitsQueue.Arn

  BenefitsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: benefits-queue

  BenefitsQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref BenefitsQueue
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sqs:SendMessage
            Resource: !GetAtt BenefitsQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !GetAtt EventBus.Arn

  EventBusQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - "*"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sqs:SendMessage
            Resource: "arn:aws:sqs:*:*:*"
            Condition:
              ArnEquals:
                aws:SourceArn: !GetAtt EventBus.Arn

  LambdaBenefitsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: lambda-benefits-function
      Handler: index.lambda_handler
      Runtime: nodejs22.x
      CodeUri: ../lambda-benefits-function/dist
      MemorySize: 128
      Timeout: 28
      Architectures:
        - arm64
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          ENV: production
          BuildTimestamp: !Ref BuildTimestamp
      Events:
        BenefitsQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt BenefitsQueue.Arn

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaPaymentPolicy
          PolicyDocument:
            Fn::Transform:
              Name: AWS::Include
              Parameters:
                Location: ../permissions/lambda-payment-permissions.json
        - PolicyName: LambdaBenefitsPolicy
          PolicyDocument:
            Fn::Transform:
              Name: AWS::Include
              Parameters:
                Location: ../permissions/lambda-benefits-permissions.json

  EventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: tcc-event-bus

Parameters:
  BuildTimestamp:
    Type: String
    Description: Timestamp to force Lambda update
