name: Deploy Lambda Function

on:
  push:
    branches:
      - main
    paths:
      - 'iac/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Check AWS CLI version
      - name: Check AWS CLI version
        run: aws --version

      # Set up AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Debug AWS credentials
      - name: Debug AWS credentials
        run: aws sts get-caller-identity

      # Validate the SAM template
      - name: Validate SAM template
        run: sam validate --template-file iac/template.yaml

      # Build the SAM application
      - name: Build SAM application
        run: sam build --template-file iac/template.yaml

      # Package the SAM application
      - name: Package SAM application
        run: sam package --template-file iac/template.yaml --output-template-file packaged.yaml --s3-bucket ${{ secrets.S3_BUCKET_NAME }} --region sa-east-1

      # Deploy the SAM application
      - name: Deploy SAM application
        run: sam deploy --template-file packaged.yaml --stack-name my-lambda-stack --capabilities CAPABILITY_IAM --region sa-east-1
