name: Deploy Lambda Function

on:
  push:
    branches:
      - main
    paths:
      - 'iac/**'
      - 'lambda-payment-function/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Check AWS CLI version
      - name: Check AWS CLI version
        run: aws --version

      # Set up AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      # Debug AWS credentials
      - name: Debug AWS credentials
        run: aws sts get-caller-identity

      # Install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: lambda-payment-function

      # Build the Lambda function
      - name: Build Lambda function
        run: npm run build
        working-directory: lambda-payment-function

      # Validate the SAM template
      - name: Validate SAM template
        run: sam validate --template-file iac/template.yaml

      # Verify S3 bucket exists
      - name: Verify S3 bucket exists
        run: aws s3 ls s3://${{ secrets.S3_BUCKET_NAME }} --region sa-east-1

      # Deploy the SAM application
      - name: Deploy SAM application
        run: |
          sam deploy --template-file iac/template.yaml \
            --stack-name my-lambda-stack \
            --capabilities CAPABILITY_IAM \
            --region sa-east-1 \
            --parameter-overrides BuildTimestamp=$(date +%s)
